### ISSUE TITLE
dependency error 

### ISSUE THREAD

**Issue by Arykee** [araujo88/password-manager#4]
from playhouse.sqlcipher_ext import *
ModuleNotFoundError: No module named 'playhouse'

**Comment by leo-aa88** [comment]
You need to follow the steps as described in the README.md file to install the dependencies. It is recommended that you install using a virtual environment. Here are the steps.

1.  Install virtualenv: `pip3 install virtualenv`
2. Create virtual environment: `virtualenv env`
3. Activate virtual environment: `source env/bin/activate`
4. Install requirements: `pip3 install -r requirements.txt`
